COMMENT ON TABLE person_discounts IS 'Таблица, показывающая у какого человека в какой пиццерии есть скидка, которая завсисит от количества заказов в данной пиццерии';
COMMENT ON COLUMN person_discounts.person_id IS 'Person_id - внешний ключ, связанный с атрибутом id отношения person';
COMMENT ON COLUMN person_discounts.pizzeria_id IS 'Pizzeria_id - внешний ключ, связанный с атрибутом id отношения pizzeria';
COMMENT ON COLUMN person_discounts.discount IS 'Скидка данного person_id в данном pizzeria_id';
COMMENT ON COLUMN person_discounts.id IS 'Идентификатор таблицы, являющийся первичным ключом';
SELECT col_description('person_discounts'::regclass, 1);
SELECT col_description('person_discounts'::regclass, 2);
SELECT col_description('person_discounts'::regclass, 3);
SELECT col_description('person_discounts'::regclass, 4);
SELECT obj_description('person_discounts'::regclass);