version: '3.8'

services:
  reddit:
    build: ./
    command: ./wait.sh db ./reddit -env=./env/docker/.env -type_memory=true
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_PASSWORD=45hekmrf
      - DB_USER=alex
      - DB_TABLE=reddit
    networks:
      - reddit-network

  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=alex
      - POSTGRES_PASSWORD=45hekmrf
      - POSTGRES_DB=reddit
    ports:
      - 5436:5432
    networks:
      - reddit-network

networks:
  reddit-network:
    driver: bridge