// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"
)

// NewBuyCandyParams создает новый объект BuyCandyParams
//
// В спецификации не определены значения по умолчанию.
func NewBuyCandyParams() BuyCandyParams {

	return BuyCandyParams{}
}

// BuyCandyParams contains all the bound params for the buy candy operation
// typically these are obtained from a http.Request
//
// swagger:parameters buyCandy
type BuyCandyParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*summary of the candy order
	  In: body
	*/
	Order BuyCandyBody
}

// BindRequest одновременно связывает и проверяет запрос, он предполагает, что сложные вещи реализуют интерфейс ошибки Validatable(strfmt.Registry)
// для простых значений будут использоваться прямые вызовы методов.
//
// Чтобы обеспечить значения по умолчанию, структура должна быть заранее инициализирована с помощью NewBuyCandyParams().
func (o *BuyCandyParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body BuyCandyBody
		// Consume выполняет привязку значений запроса, переносит значения из r.Body в &body
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("order", "body", "", err))
		} else {
			// Далее присходит валидация данных в &body, были ли все значения переданы
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}
			// Считывается контекст запроса и проверяется соотсветсвию контекста ответа
			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Order = body
			}
		}
	}
	if len(res) > 0 {
		// Превращает срез ошибок в структуру содержащую этот срез соответствующую
		// интерфейсу error
		return errors.CompositeValidationError(res...)
	}
	return nil
}
